---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-app-svc-acc
  namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  name: api-app-service
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: api-app
  ports:
    - protocol: TCP
      port: 3033
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  template:
    metadata:
      labels:
        app: api-app
    spec:
      serviceAccountName: api-app-svc-acc
      containers:
        - name: api-app-container
          image: localhost:5000/api-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: CONJUR_APPLIANCE_URL
              value: https://conjur-oss.conjur-server.svc.cluster.local
            - name: CONJUR_ACCOUNT
              value: default
            - name: CONJUR_AUTHN_JWT_SERVICE_ID
              value: kubernetes
            - name: CONJUR_SSL_CERTIFICATE
              valueFrom:
                configMapKeyRef:
                  key: ssl-certificate
                  name: conjur-ssl-cert
